name: Deploy Production

on:
  push:
    branches:
      - production

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
      CDN_DISTRIBUTION_ID: ${{ secrets.CDN_DISTRIBUTION_ID }}
      CDN_INVALIDATION_PATH: ${{ secrets.CDN_INVALIDATION_PATH }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Deploy Production
        run: make deploy-production
